export const CHANGE_EDITOR_DATA = 'CHANGE_EDITOR_DATA'
export const UPLOAD_MAP = 'UPLOAD_MAP'
export const UPDATE_MAP = 'UPDATE_MAP'
export const RESET_MAP = 'RESET_MAP'
export const ADD_TILESET = 'ADD_TILESET'
