/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Command = Talk | ChangeCharDir | MoveCharTo | HideChar | Wait | IfElse;
export type Text = string;
export type Direction = "Up" | "Down" | "Left" | "Right";
export type X = number;
export type Y = number;
export type WaitTimeInMilliseconds = number;
export type Conditions = [Condition, ...Condition[]];
export type Condition = MoreOrEqualThanXMonster | IsTimeOfDay;
export type ListOfCommands = Command[];

/**
 * Dynamic game event
 */
export interface GameEvent {
  commands: ListOfCommands;
}
export interface Talk {
  type: "talk";
  text: Text;
  [k: string]: any;
}
export interface ChangeCharDir {
  type: "change_char_dir";
  dir: Direction;
  [k: string]: any;
}
export interface MoveCharTo {
  type: "move_char_to";
  x: X;
  y: Y;
  [k: string]: any;
}
export interface HideChar {
  type: "hide_char";
  [k: string]: any;
}
export interface Wait {
  type: "wait";
  milliseconds: WaitTimeInMilliseconds;
  [k: string]: any;
}
export interface IfElse {
  type: "if_else";
  conditions: Conditions;
  ifCommands?: Command[];
  elseCommands?: Command[];
  [k: string]: any;
}
export interface MoreOrEqualThanXMonster {
  type: "more_or_equal_than_x_monster";
  numberMonsters: number;
  [k: string]: any;
}
export interface IsTimeOfDay {
  type: "is_time_of_day";
  time: "morning" | "afternoon" | "evening" | "night";
  [k: string]: any;
}
